substitutions:
  # -------------------------------------------------------------
  # MANDATORY ORCON SETUP
  # -------------------------------------------------------------
  
  # Your Orcon Unit's ID (Found on the green sticker inside the Orcon box)
  # Convert the 3 hex bytes to decimal. 
  # Example: 76 24 94 hex -> 118, 36, 148 dec
  orcon_dest_id_0: "118"
  orcon_dest_id_1: "36"
  orcon_dest_id_2: "148"

  # Your ESP32's unique Remote ID. 
  # This can be any arbitrary integers (1-254) as long as it's unique on your network.
  esp32_source_id_0: "11"
  esp32_source_id_1: "22"
  esp32_source_id_2: "33"

  # -------------------------------------------------------------
  # OPTIONAL: KNOWN REMOTES
  # -------------------------------------------------------------
  
  # To sync Home Assistant's state when you use your physical Orcon remote,
  # you must register its ID here. Check the ESPHome logs when pressing a button
  # on your physical remote to see its ID intercepted.
  remote1_id: '"11,22,33"'
  remote1_name: '"Physical Remote"'

esphome:
  name: fancontrol
  includes: 
    - itho-lib/CC1101.h
    - itho-lib/CC1101.cpp
    - itho-lib/CC1101Packet.h
    - itho-lib/IthoCC1101.h
    - itho-lib/IthoCC1101.cpp
    - itho-lib/IthoPacket.h
    - itho.h
  platformio_options:
    lib_deps:
      - "SPI"

  on_boot:
    then:
      - lambda: |-
          Idlist[0]={${remote1_id}, ${remote1_name}};
          Idlist[1]={"",""};
          Idlist[2]={"",""};
          // Arbitrary integers between 1-254 for ESP32's ID
          srcID[0] = ${esp32_source_id_0};
          srcID[1] = ${esp32_source_id_1};
          srcID[2] = ${esp32_source_id_2};
          // CLEARLY MARKED: Edit these below to match your destination Orcon Ventilation System ID
          destID[0] = ${orcon_dest_id_0};
          destID[1] = ${orcon_dest_id_1};
          destID[2] = ${orcon_dest_id_2};
          Mydeviceid="Homeassistant"; 
          setup_itho();

  on_loop:
    - lambda: |-
        loop_itho();

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: Orcon ESP32 Fallback Hotspot
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
#  level: VERBOSE #Enable this line to find out the ID of youre remote

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret ota_password
interval:
  - interval: 1s
    then:
      - lambda: |-
          update_itho(id(itho_fanspeed), id(itho_fantimer), id(itho_lastid));

switch:
  - platform: template
    name: "FanSendStandby"
    id: fansendstandby
    turn_on_action:
      - lambda: |-
          rf->sendCommand(OrconStandBy, srcID, destID);
          State = 100;
          Timer = 0;
          LastID = Mydeviceid;
          rf->initReceive();
          id(fansendstandby).publish_state(false);

  - platform: template
    name: "FanSendLow"
    id: fansendlow
    turn_on_action:
      - lambda: |-
          rf->sendCommand(OrconLow, srcID, destID);
          State = 101;
          Timer = 0;
          LastID = Mydeviceid;
          rf->initReceive();
          id(fansendlow).publish_state(false);

  - platform: template
    name: "FanSendMedium"
    id: fansendmedium
    turn_on_action:
      - lambda: |-
          rf->sendCommand(OrconMedium, srcID, destID);
          State = 102;
          Timer = 0;
          LastID = Mydeviceid;
          rf->initReceive();
          id(fansendmedium).publish_state(false);

  - platform: template
    name: "FanSendHigh"
    id: fansendhigh
    turn_on_action:
      - lambda: |-
          rf->sendCommand(OrconHigh, srcID, destID);
          State = 103;
          Timer = 0;
          LastID = Mydeviceid;
          rf->initReceive();
          id(fansendhigh).publish_state(false);

  - platform: template
    name: "FanSendAuto"
    id: fansendauto
    turn_on_action:
      - lambda: |-
          rf->sendCommand(OrconAuto, srcID, destID);
          State = 104;
          Timer = 0;
          LastID = Mydeviceid;
          rf->initReceive();
          id(fansendauto).publish_state(false);

text_sensor:
  - platform: template
    name: "fanspeed"
    id: itho_fanspeed
    icon: "mdi:transfer"
  - platform: template
    name: "fantimer"
    id: itho_fantimer
    icon: "mdi:timer"
  - platform: template
    name: "lastid"
    id: itho_lastid
